[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.tokenizer", "php82Extensions.pdo", "nodejs_20"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install && npm run build",
    "php artisan view:clear",
    "php artisan cache:clear",
    "php artisan config:clear",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
